### ISSUE TITLE
VirusTotal scan, possible malware?

### ISSUE THREAD

**Issue by Sakooooo** [RustyBalboadev/Discord-Raid-Tool#7]
https://www.virustotal.com/gui/file/0539cb677684ec9500dead2e136fc1dd4969b7d5c4ec84bc18a5d6ef203b1484/detection checked behavior looks really weird it says it deletes some registry keys and runs some commands that it detects. please tell me if its safe?

**Comment by rustybalboadev** [comment]
This is nothing but a false positive, you're on github. View the code if you think there is a virus & build from source.

**Comment by Sakooooo** [comment]
Ok thanks! also I don't know how to build from source

**Comment by Sakooooo** [comment]
If you could could you tell me how to build from source?
