### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Sakooooo** [RustyBalboadev/Discord-Raid-Tool#8]
Crashes everytime I press start spamming anyone know why? it was able to invite them to the server though

**Comment by Sakooooo** [comment]
It was able to invite though

**Comment by rustybalboadev** [comment]
Do you have the latest version?

**Comment by Sakooooo** [comment]
Wait let me check

**Comment by Sakooooo** [comment]
I have the latest version I think when I installed it with the link in the readme

**Comment by Sakooooo** [comment]
I just tried installing it from the releases tab and I am still crashing when pressing start spamming

**Comment by rustybalboadev** [comment]
Couple of things
* Are you sure your tokens are valid
* Are you sure you're following the correct inputs with the examples on the input placeholders?

**Comment by ghost** [comment]
situation can vmaybe not b correlation to crusty program maybe due to your window depdencys... plz update miecrosoft netfram work to 4.9 or latest
