### ISSUE TITLE
Crash after clicking the chat spam button.

### ISSUE THREAD

**Issue by Xenobotical** [RustyBalboadev/Discord-Raid-Tool#9]
l click the chat spam button, and the program crashes.

**Comment by rustybalboadev** [comment]
Do you have the latest version [here](https://github.com/RustyBalboadev/Discord-Raid-Tool/releases/tag/v1.4) ?

**Comment by Xenobotical** [comment]
Yes i do have the latest version.

**Comment by rustybalboadev** [comment]
1. Is all of your tokens valid
2. Make sure your tokens.txt file is laid out properly leaving each token on a new line
3. Does the program show any error messages before crashing?

**Comment by Xenobotical** [comment]
All tokens were valid, all tokens were on new lines, and it did the white screen freeze and said that the program froze and needs to be closed

**Comment by rustybalboadev** [comment]
If you have discord can you message me there "Rusty_Balboa#0666"
